### ISSUE TITLE
Can't make requests

### ISSUE THREAD

**Issue by wurgo** [obs-websocket-community-projects/obs-websocket-java#138]
# Describe the bug
Every time I make a getRecordStatusRequest request it throws an error.

# Code Sample
```java
CONTROLLER.getRecordStatusRequest(response -> recording[0] = response.getMessageData().getResponseData().getOutputActive());
```

# Expected behavior
It should work 🤷🏼 

# Additional context
Here is the error:
```
[19:46:26] [WebSocketClient@862428563-102/ERROR] (LoggingCommunicatorLifecycleListener) onError: Message received was not valid json: {"d":{"requestId":"17bdaf76-1c9d-4b5d-9d3a-c72013e56554","requestStatus":{"code":100,"result":true},"requestType":"GetRecordStatus","responseData":{"outputActive":true,"outputBytes":4635262961,"outputDuration":741608,"outputPaused":false,"outputTimecode":"00:12:21.608"}},"op":7}
 com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "00:12:21.608"
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:320) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:310) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:991) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:163) ~[gson-2.9.0.jar:?]
	at io.obswebsocket.community.client.message.response.RequestResponseSerialization.deserialize(RequestResponseSerialization.java:34) ~[obs-websocket-java-develop-SNAPSHOT.jar:?]
	at io.obswebsocket.community.client.message.response.RequestResponseSerialization.deserialize(RequestResponseSerialization.java:13) ~[obs-websocket-java-develop-SNAPSHOT.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:991) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:163) ~[gson-2.9.0.jar:?]
	at io.obswebsocket.community.client.message.MessageSerialization.deserialize(MessageSerialization.java:31) ~[obs-websocket-java-develop-SNAPSHOT.jar:?]
	at io.obswebsocket.community.client.message.MessageSerialization.deserialize(MessageSerialization.java:13) ~[obs-websocket-java-develop-SNAPSHOT.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:991) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:956) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:905) ~[gson-2.9.0.jar:?]
	at io.obswebsocket.community.client.translator.GsonMessageTranslator.fromJson(GsonMessageTranslator.java:35) ~[obs-websocket-java-develop-SNAPSHOT.jar:?]
	at io.obswebsocket.community.client.OBSCommunicator.onMessage(OBSCommunicator.java:158) [obs-websocket-java-develop-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:301) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:67) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:287) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:152) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:326) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:202) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:225) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame(Parser.java:259) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:459) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:440) [websocket-common-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.49.v20220914.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.49.v20220914.jar:?]
```

**Comment by ChristopheCVB** [comment]
As you may expect with a SNAPSHOT build, it can be unstable ;)
